baseURL = "https://xingminw.github.io/"
defaultContentLanguage = 'en-us'
theme = "sime"
disableKinds = ["taxonomy", "term"]

name = "Xingmin Wang"
title = "Curriculum Vitae"
description = "Traffic Network Model, Traffic Flow Theory, Connected and Automated Transportation"
job = "Ph.D. Candidate"
copyright = "[Copyright © Xingmin Wang](https://xingminw.github.io/)"


[markup.goldmark.renderer]
unsafe = true
hardWraps = true
